const example = {
  location: {
    name: "Sarasota",
    region: "Florida",
    country: "United States of America",
    lat: 27.34,
    lon: -82.53,
    tz_id: "America/New_York",
    localtime_epoch: 1695415121,
    localtime: "2023-09-22 16:38",
  },
  current: {
    last_updated_epoch: 1695414600,
    last_updated: "2023-09-22 16:30",
    temp_c: 32.2,
    temp_f: 90,
    is_day: 1,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003,
    },
    wind_mph: 6.9,
    wind_kph: 11.2,
    wind_degree: 40,
    wind_dir: "NE",
    pressure_mb: 1011,
    pressure_in: 29.85,
    precip_mm: 0,
    precip_in: 0,
    humidity: 45,
    cloud: 25,
    feelslike_c: 38.2,
    feelslike_f: 100.8,
    vis_km: 16,
    vis_miles: 9,
    uv: 6,
    gust_mph: 8.6,
    gust_kph: 13.8,
  },
  forecast: {
    forecastday: [
      {
        date: "2023-09-22",
        date_epoch: 1695340800,
        day: {
          maxtemp_c: 30.2,
          maxtemp_f: 86.4,
          mintemp_c: 22.5,
          mintemp_f: 72.5,
          avgtemp_c: 26.3,
          avgtemp_f: 79.3,
          maxwind_mph: 10.1,
          maxwind_kph: 16.2,
          totalprecip_mm: 1.48,
          totalprecip_in: 0.06,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 84,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 6,
        },
        astro: {
          sunrise: "07:19 AM",
          sunset: "07:27 PM",
          moonrise: "02:25 PM",
          moonset: "No moonset",
          moon_phase: "First Quarter",
          moon_illumination: "41",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1695355200,
            time: "2023-09-22 00:00",
            temp_c: 25.7,
            temp_f: 78.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 66,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 27,
            feelslike_c: 28.5,
            feelslike_f: 83.2,
            windchill_c: 25.7,
            windchill_f: 78.3,
            heatindex_c: 28.5,
            heatindex_f: 83.2,
            dewpoint_c: 22.9,
            dewpoint_f: 73.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.7,
            gust_kph: 25.2,
            uv: 1,
          },
          {
            time_epoch: 1695358800,
            time: "2023-09-22 01:00",
            temp_c: 25.3,
            temp_f: 77.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 69,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 86,
            cloud: 41,
            feelslike_c: 27.9,
            feelslike_f: 82.3,
            windchill_c: 25.3,
            windchill_f: 77.5,
            heatindex_c: 27.9,
            heatindex_f: 82.3,
            dewpoint_c: 22.8,
            dewpoint_f: 73.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.9,
            gust_kph: 23.9,
            uv: 1,
          },
          {
            time_epoch: 1695362400,
            time: "2023-09-22 02:00",
            temp_c: 24.7,
            temp_f: 76.5,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 67,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 1.48,
            precip_in: 0.06,
            humidity: 87,
            cloud: 85,
            feelslike_c: 27.1,
            feelslike_f: 80.7,
            windchill_c: 24.7,
            windchill_f: 76.5,
            heatindex_c: 27.1,
            heatindex_f: 80.7,
            dewpoint_c: 22.3,
            dewpoint_f: 72.2,
            will_it_rain: 1,
            chance_of_rain: 84,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.6,
            gust_kph: 21.9,
            uv: 1,
          },
          {
            time_epoch: 1695366000,
            time: "2023-09-22 03:00",
            temp_c: 24.2,
            temp_f: 75.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 56,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 18,
            feelslike_c: 26.5,
            feelslike_f: 79.7,
            windchill_c: 24.2,
            windchill_f: 75.6,
            heatindex_c: 26.5,
            heatindex_f: 79.7,
            dewpoint_c: 22.2,
            dewpoint_f: 71.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.5,
            gust_kph: 21.7,
            uv: 1,
          },
          {
            time_epoch: 1695369600,
            time: "2023-09-22 04:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 50,
            wind_dir: "NE",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 14,
            feelslike_c: 26.1,
            feelslike_f: 79,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 26.1,
            heatindex_f: 79,
            dewpoint_c: 22.1,
            dewpoint_f: 71.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.8,
            uv: 1,
          },
          {
            time_epoch: 1695373200,
            time: "2023-09-22 05:00",
            temp_c: 23,
            temp_f: 73.4,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 41,
            wind_dir: "NE",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 49,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 23,
            windchill_f: 73.4,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 22.1,
            dewpoint_f: 71.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.8,
            gust_kph: 20.5,
            uv: 1,
          },
          {
            time_epoch: 1695376800,
            time: "2023-09-22 06:00",
            temp_c: 22.8,
            temp_f: 73,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 43,
            wind_dir: "NE",
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 85,
            feelslike_c: 25.2,
            feelslike_f: 77.4,
            windchill_c: 22.8,
            windchill_f: 73,
            heatindex_c: 25.2,
            heatindex_f: 77.4,
            dewpoint_c: 22,
            dewpoint_f: 71.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.9,
            gust_kph: 20.8,
            uv: 1,
          },
          {
            time_epoch: 1695380400,
            time: "2023-09-22 07:00",
            temp_c: 22.6,
            temp_f: 72.7,
            is_day: 0,
            condition: {
              text: "Fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 42,
            wind_dir: "NE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 25.1,
            feelslike_f: 77.1,
            windchill_c: 22.6,
            windchill_f: 72.7,
            heatindex_c: 25.1,
            heatindex_f: 77.1,
            dewpoint_c: 22.1,
            dewpoint_f: 71.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.6,
            gust_kph: 21.9,
            uv: 1,
          },
          {
            time_epoch: 1695384000,
            time: "2023-09-22 08:00",
            temp_c: 22.5,
            temp_f: 72.5,
            is_day: 1,
            condition: {
              text: "Fog",
              icon: "//cdn.weatherapi.com/weather/64x64/day/248.png",
              code: 1135,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 48,
            wind_dir: "NE",
            pressure_mb: 1014,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 25,
            feelslike_f: 77,
            windchill_c: 22.5,
            windchill_f: 72.5,
            heatindex_c: 25,
            heatindex_f: 77,
            dewpoint_c: 22,
            dewpoint_f: 71.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.6,
            gust_kph: 20.3,
            uv: 5,
          },
          {
            time_epoch: 1695387600,
            time: "2023-09-22 09:00",
            temp_c: 22.8,
            temp_f: 73,
            is_day: 1,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
              code: 1030,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 51,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 66,
            feelslike_c: 25.2,
            feelslike_f: 77.4,
            windchill_c: 22.8,
            windchill_f: 73,
            heatindex_c: 25.2,
            heatindex_f: 77.4,
            dewpoint_c: 22.1,
            dewpoint_f: 71.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.4,
            gust_kph: 19.9,
            uv: 5,
          },
          {
            time_epoch: 1695391200,
            time: "2023-09-22 10:00",
            temp_c: 23.9,
            temp_f: 75,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 51,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 76,
            feelslike_c: 26.2,
            feelslike_f: 79.2,
            windchill_c: 23.9,
            windchill_f: 75,
            heatindex_c: 26.2,
            heatindex_f: 79.2,
            dewpoint_c: 22.2,
            dewpoint_f: 72,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 5,
          },
          {
            time_epoch: 1695394800,
            time: "2023-09-22 11:00",
            temp_c: 25,
            temp_f: 77,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 50,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 50,
            feelslike_c: 27.5,
            feelslike_f: 81.5,
            windchill_c: 25,
            windchill_f: 77,
            heatindex_c: 27.5,
            heatindex_f: 81.5,
            dewpoint_c: 22.6,
            dewpoint_f: 72.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.4,
            gust_kph: 16.7,
            uv: 7,
          },
          {
            time_epoch: 1695398400,
            time: "2023-09-22 12:00",
            temp_c: 26.4,
            temp_f: 79.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 46,
            feelslike_c: 29.4,
            feelslike_f: 84.9,
            windchill_c: 26.4,
            windchill_f: 79.5,
            heatindex_c: 29.4,
            heatindex_f: 84.9,
            dewpoint_c: 23.1,
            dewpoint_f: 73.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.1,
            gust_kph: 16.2,
            uv: 7,
          },
          {
            time_epoch: 1695402000,
            time: "2023-09-22 13:00",
            temp_c: 28.3,
            temp_f: 82.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 33,
            wind_dir: "NNE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 76,
            cloud: 19,
            feelslike_c: 32.3,
            feelslike_f: 90.2,
            windchill_c: 28.3,
            windchill_f: 82.9,
            heatindex_c: 32.3,
            heatindex_f: 90.2,
            dewpoint_c: 23.6,
            dewpoint_f: 74.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 7,
          },
          {
            time_epoch: 1695405600,
            time: "2023-09-22 14:00",
            temp_c: 29.7,
            temp_f: 85.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 23,
            wind_dir: "NNE",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            humidity: 67,
            cloud: 29,
            feelslike_c: 33.8,
            feelslike_f: 92.9,
            windchill_c: 29.7,
            windchill_f: 85.5,
            heatindex_c: 33.8,
            heatindex_f: 92.9,
            dewpoint_c: 23,
            dewpoint_f: 73.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8,
            gust_kph: 12.9,
            uv: 7,
          },
          {
            time_epoch: 1695409200,
            time: "2023-09-22 15:00",
            temp_c: 30.2,
            temp_f: 86.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 14,
            wind_dir: "NNE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 62,
            cloud: 56,
            feelslike_c: 33.8,
            feelslike_f: 92.9,
            windchill_c: 30.2,
            windchill_f: 86.4,
            heatindex_c: 33.8,
            heatindex_f: 92.9,
            dewpoint_c: 22.1,
            dewpoint_f: 71.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7,
            gust_kph: 11.3,
            uv: 8,
          },
          {
            time_epoch: 1695412800,
            time: "2023-09-22 16:00",
            temp_c: 32.2,
            temp_f: 90,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 40,
            wind_dir: "NE",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 45,
            cloud: 25,
            feelslike_c: 33,
            feelslike_f: 91.4,
            windchill_c: 29.8,
            windchill_f: 85.6,
            heatindex_c: 33,
            heatindex_f: 91.4,
            dewpoint_c: 21.7,
            dewpoint_f: 71,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 16,
            vis_miles: 9,
            gust_mph: 8.6,
            gust_kph: 13.8,
            uv: 6,
          },
          {
            time_epoch: 1695416400,
            time: "2023-09-22 17:00",
            temp_c: 29.6,
            temp_f: 85.3,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 17,
            wind_dir: "NNE",
            pressure_mb: 1011,
            pressure_in: 29.86,
            precip_mm: 0,
            precip_in: 0,
            humidity: 61,
            cloud: 81,
            feelslike_c: 32.6,
            feelslike_f: 90.6,
            windchill_c: 29.6,
            windchill_f: 85.3,
            heatindex_c: 32.6,
            heatindex_f: 90.6,
            dewpoint_c: 21.4,
            dewpoint_f: 70.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.4,
            gust_kph: 16.8,
            uv: 6,
          },
          {
            time_epoch: 1695420000,
            time: "2023-09-22 18:00",
            temp_c: 29.5,
            temp_f: 85.1,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 32,
            wind_dir: "NNE",
            pressure_mb: 1011,
            pressure_in: 29.86,
            precip_mm: 0,
            precip_in: 0,
            humidity: 60,
            cloud: 83,
            feelslike_c: 32.1,
            feelslike_f: 89.9,
            windchill_c: 29.5,
            windchill_f: 85.1,
            heatindex_c: 32.1,
            heatindex_f: 89.9,
            dewpoint_c: 20.9,
            dewpoint_f: 69.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.7,
            gust_kph: 18.8,
            uv: 6,
          },
          {
            time_epoch: 1695423600,
            time: "2023-09-22 19:00",
            temp_c: 29.3,
            temp_f: 84.7,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 42,
            wind_dir: "NE",
            pressure_mb: 1011,
            pressure_in: 29.86,
            precip_mm: 0,
            precip_in: 0,
            humidity: 59,
            cloud: 68,
            feelslike_c: 31.7,
            feelslike_f: 89.1,
            windchill_c: 29.3,
            windchill_f: 84.7,
            heatindex_c: 31.7,
            heatindex_f: 89.1,
            dewpoint_c: 20.6,
            dewpoint_f: 69,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 6,
          },
          {
            time_epoch: 1695427200,
            time: "2023-09-22 20:00",
            temp_c: 29,
            temp_f: 84.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 29,
            wind_dir: "NNE",
            pressure_mb: 1011,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            humidity: 61,
            cloud: 45,
            feelslike_c: 31.5,
            feelslike_f: 88.7,
            windchill_c: 29,
            windchill_f: 84.2,
            heatindex_c: 31.5,
            heatindex_f: 88.7,
            dewpoint_c: 20.8,
            dewpoint_f: 69.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1,
          },
          {
            time_epoch: 1695430800,
            time: "2023-09-22 21:00",
            temp_c: 28.7,
            temp_f: 83.7,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 26,
            wind_dir: "NNE",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            humidity: 64,
            cloud: 79,
            feelslike_c: 31.3,
            feelslike_f: 88.3,
            windchill_c: 28.7,
            windchill_f: 83.7,
            heatindex_c: 31.3,
            heatindex_f: 88.3,
            dewpoint_c: 21.1,
            dewpoint_f: 70,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7,
            gust_kph: 11.3,
            uv: 1,
          },
          {
            time_epoch: 1695434400,
            time: "2023-09-22 22:00",
            temp_c: 28.1,
            temp_f: 82.6,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 58,
            wind_dir: "ENE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 67,
            cloud: 99,
            feelslike_c: 30.7,
            feelslike_f: 87.3,
            windchill_c: 28.1,
            windchill_f: 82.6,
            heatindex_c: 30.7,
            heatindex_f: 87.3,
            dewpoint_c: 21.4,
            dewpoint_f: 70.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.3,
            uv: 1,
          },
          {
            time_epoch: 1695438000,
            time: "2023-09-22 23:00",
            temp_c: 26.4,
            temp_f: 79.5,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 79,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 76,
            cloud: 98,
            feelslike_c: 28.9,
            feelslike_f: 83.9,
            windchill_c: 26.4,
            windchill_f: 79.5,
            heatindex_c: 28.9,
            heatindex_f: 83.9,
            dewpoint_c: 21.9,
            dewpoint_f: 71.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.1,
            gust_kph: 16.3,
            uv: 1,
          },
        ],
      },
      {
        date: "2023-09-23",
        date_epoch: 1695427200,
        day: {
          maxtemp_c: 32.8,
          maxtemp_f: 91,
          mintemp_c: 23,
          mintemp_f: 73.4,
          avgtemp_c: 27.1,
          avgtemp_f: 80.7,
          maxwind_mph: 12.5,
          maxwind_kph: 20.2,
          totalprecip_mm: 0.03,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 9.9,
          avgvis_miles: 6,
          avghumidity: 62,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          uv: 7,
        },
        astro: {
          sunrise: "07:19 AM",
          sunset: "07:26 PM",
          moonrise: "03:25 PM",
          moonset: "12:39 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: "52",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1695441600,
            time: "2023-09-23 00:00",
            temp_c: 25.2,
            temp_f: 77.4,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 82,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 98,
            feelslike_c: 27.4,
            feelslike_f: 81.4,
            windchill_c: 25.2,
            windchill_f: 77.4,
            heatindex_c: 27.4,
            heatindex_f: 81.4,
            dewpoint_c: 21.8,
            dewpoint_f: 71.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 12.1,
            gust_kph: 19.5,
            uv: 1,
          },
          {
            time_epoch: 1695445200,
            time: "2023-09-23 01:00",
            temp_c: 24.8,
            temp_f: 76.6,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 84,
            cloud: 87,
            feelslike_c: 27.1,
            feelslike_f: 80.7,
            windchill_c: 24.8,
            windchill_f: 76.6,
            heatindex_c: 27.1,
            heatindex_f: 80.7,
            dewpoint_c: 22,
            dewpoint_f: 71.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 11.3,
            gust_kph: 18.2,
            uv: 1,
          },
          {
            time_epoch: 1695448800,
            time: "2023-09-23 02:00",
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 84,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 70,
            feelslike_c: 26.8,
            feelslike_f: 80.3,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 26.8,
            heatindex_f: 80.3,
            dewpoint_c: 21.9,
            dewpoint_f: 71.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 11.7,
            gust_kph: 18.8,
            uv: 1,
          },
          {
            time_epoch: 1695452400,
            time: "2023-09-23 03:00",
            temp_c: 24.4,
            temp_f: 75.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 87,
            wind_dir: "E",
            pressure_mb: 1012,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 53,
            feelslike_c: 26.5,
            feelslike_f: 79.7,
            windchill_c: 24.4,
            windchill_f: 75.9,
            heatindex_c: 26.5,
            heatindex_f: 79.7,
            dewpoint_c: 21.3,
            dewpoint_f: 70.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.8,
            gust_kph: 20.5,
            uv: 1,
          },
          {
            time_epoch: 1695456000,
            time: "2023-09-23 04:00",
            temp_c: 24.2,
            temp_f: 75.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1012,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            humidity: 79,
            cloud: 52,
            feelslike_c: 26.1,
            feelslike_f: 79,
            windchill_c: 24.2,
            windchill_f: 75.6,
            heatindex_c: 26.1,
            heatindex_f: 79,
            dewpoint_c: 20.2,
            dewpoint_f: 68.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.8,
            uv: 1,
          },
          {
            time_epoch: 1695459600,
            time: "2023-09-23 05:00",
            temp_c: 23.9,
            temp_f: 75,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 76,
            wind_dir: "ENE",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            humidity: 72,
            cloud: 56,
            feelslike_c: 25.6,
            feelslike_f: 78.2,
            windchill_c: 23.9,
            windchill_f: 75,
            heatindex_c: 25.6,
            heatindex_f: 78.2,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.8,
            gust_kph: 20.5,
            uv: 1,
          },
          {
            time_epoch: 1695463200,
            time: "2023-09-23 06:00",
            temp_c: 23.3,
            temp_f: 73.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 78,
            wind_dir: "ENE",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 55,
            feelslike_c: 25.2,
            feelslike_f: 77.3,
            windchill_c: 23.3,
            windchill_f: 73.9,
            heatindex_c: 25.2,
            heatindex_f: 77.3,
            dewpoint_c: 17.3,
            dewpoint_f: 63.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.2,
            gust_kph: 21.3,
            uv: 1,
          },
          {
            time_epoch: 1695466800,
            time: "2023-09-23 07:00",
            temp_c: 23,
            temp_f: 73.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 68,
            cloud: 53,
            feelslike_c: 25,
            feelslike_f: 77,
            windchill_c: 23,
            windchill_f: 73.4,
            heatindex_c: 25,
            heatindex_f: 77,
            dewpoint_c: 16.9,
            dewpoint_f: 62.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.7,
            gust_kph: 22.1,
            uv: 1,
          },
          {
            time_epoch: 1695470400,
            time: "2023-09-23 08:00",
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 77,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 66,
            cloud: 51,
            feelslike_c: 25,
            feelslike_f: 77,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 25,
            heatindex_f: 77,
            dewpoint_c: 16.5,
            dewpoint_f: 61.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 6,
          },
          {
            time_epoch: 1695474000,
            time: "2023-09-23 09:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 78,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 66,
            cloud: 33,
            feelslike_c: 25.4,
            feelslike_f: 77.8,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 25.4,
            heatindex_f: 77.8,
            dewpoint_c: 17,
            dewpoint_f: 62.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.9,
            uv: 6,
          },
          {
            time_epoch: 1695477600,
            time: "2023-09-23 10:00",
            temp_c: 25.1,
            temp_f: 77.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 82,
            wind_dir: "E",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 63,
            cloud: 26,
            feelslike_c: 26.4,
            feelslike_f: 79.5,
            windchill_c: 25.1,
            windchill_f: 77.2,
            heatindex_c: 26.4,
            heatindex_f: 79.5,
            dewpoint_c: 17.5,
            dewpoint_f: 63.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.6,
            gust_kph: 17,
            uv: 7,
          },
          {
            time_epoch: 1695481200,
            time: "2023-09-23 11:00",
            temp_c: 30,
            temp_f: 86,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 89,
            wind_dir: "E",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 54,
            cloud: 7,
            feelslike_c: 32.1,
            feelslike_f: 89.9,
            windchill_c: 30,
            windchill_f: 86,
            heatindex_c: 32.1,
            heatindex_f: 89.9,
            dewpoint_c: 19.8,
            dewpoint_f: 67.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.2,
            gust_kph: 16.4,
            uv: 8,
          },
          {
            time_epoch: 1695484800,
            time: "2023-09-23 12:00",
            temp_c: 31.1,
            temp_f: 88,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 93,
            wind_dir: "E",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 52,
            cloud: 0,
            feelslike_c: 33.6,
            feelslike_f: 92.5,
            windchill_c: 31.1,
            windchill_f: 88,
            heatindex_c: 33.6,
            heatindex_f: 92.5,
            dewpoint_c: 20.1,
            dewpoint_f: 68.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.7,
            gust_kph: 14.1,
            uv: 8,
          },
          {
            time_epoch: 1695488400,
            time: "2023-09-23 13:00",
            temp_c: 32.1,
            temp_f: 89.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 83,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 51,
            cloud: 2,
            feelslike_c: 35.3,
            feelslike_f: 95.6,
            windchill_c: 32.1,
            windchill_f: 89.8,
            heatindex_c: 35.3,
            heatindex_f: 95.6,
            dewpoint_c: 20.7,
            dewpoint_f: 69.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12,
            uv: 8,
          },
          {
            time_epoch: 1695492000,
            time: "2023-09-23 14:00",
            temp_c: 32.8,
            temp_f: 91,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 52,
            cloud: 6,
            feelslike_c: 36.9,
            feelslike_f: 98.4,
            windchill_c: 32.8,
            windchill_f: 91,
            heatindex_c: 36.9,
            heatindex_f: 98.4,
            dewpoint_c: 21.6,
            dewpoint_f: 70.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 8,
          },
          {
            time_epoch: 1695495600,
            time: "2023-09-23 15:00",
            temp_c: 30.2,
            temp_f: 86.3,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 53,
            wind_dir: "NE",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            humidity: 45,
            cloud: 68,
            feelslike_c: 31,
            feelslike_f: 87.8,
            windchill_c: 30.2,
            windchill_f: 86.3,
            heatindex_c: 31,
            heatindex_f: 87.8,
            dewpoint_c: 16.9,
            dewpoint_f: 62.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.5,
            gust_kph: 8.9,
            uv: 7,
          },
          {
            time_epoch: 1695499200,
            time: "2023-09-23 16:00",
            temp_c: 30,
            temp_f: 86,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 23,
            wind_dir: "NNE",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0.03,
            precip_in: 0,
            humidity: 46,
            cloud: 58,
            feelslike_c: 30.9,
            feelslike_f: 87.6,
            windchill_c: 30,
            windchill_f: 86,
            heatindex_c: 30.9,
            heatindex_f: 87.6,
            dewpoint_c: 17,
            dewpoint_f: 62.6,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.3,
            gust_kph: 8.5,
            uv: 7,
          },
          {
            time_epoch: 1695502800,
            time: "2023-09-23 17:00",
            temp_c: 30.3,
            temp_f: 86.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 350,
            wind_dir: "N",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 50,
            cloud: 25,
            feelslike_c: 32,
            feelslike_f: 89.6,
            windchill_c: 30.3,
            windchill_f: 86.5,
            heatindex_c: 32,
            heatindex_f: 89.6,
            dewpoint_c: 18.8,
            dewpoint_f: 65.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.1,
            gust_kph: 11.4,
            uv: 8,
          },
          {
            time_epoch: 1695506400,
            time: "2023-09-23 18:00",
            temp_c: 28.6,
            temp_f: 83.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 343,
            wind_dir: "NNW",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 54,
            cloud: 62,
            feelslike_c: 29.9,
            feelslike_f: 85.9,
            windchill_c: 28.6,
            windchill_f: 83.5,
            heatindex_c: 29.9,
            heatindex_f: 85.9,
            dewpoint_c: 18.4,
            dewpoint_f: 65.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8,
            gust_kph: 12.9,
            uv: 7,
          },
          {
            time_epoch: 1695510000,
            time: "2023-09-23 19:00",
            temp_c: 28.3,
            temp_f: 82.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 2,
            wind_dir: "N",
            pressure_mb: 1011,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            humidity: 55,
            cloud: 57,
            feelslike_c: 29.6,
            feelslike_f: 85.3,
            windchill_c: 28.3,
            windchill_f: 82.9,
            heatindex_c: 29.6,
            heatindex_f: 85.3,
            dewpoint_c: 18.4,
            dewpoint_f: 65.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.6,
            gust_kph: 13.9,
            uv: 7,
          },
          {
            time_epoch: 1695513600,
            time: "2023-09-23 20:00",
            temp_c: 28.2,
            temp_f: 82.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 21,
            wind_dir: "NNE",
            pressure_mb: 1012,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            humidity: 57,
            cloud: 42,
            feelslike_c: 29.7,
            feelslike_f: 85.4,
            windchill_c: 28.2,
            windchill_f: 82.8,
            heatindex_c: 29.7,
            heatindex_f: 85.4,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.7,
            gust_kph: 17.2,
            uv: 1,
          },
          {
            time_epoch: 1695517200,
            time: "2023-09-23 21:00",
            temp_c: 28.1,
            temp_f: 82.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 34,
            wind_dir: "NE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 54,
            cloud: 47,
            feelslike_c: 29.3,
            feelslike_f: 84.7,
            windchill_c: 28.1,
            windchill_f: 82.6,
            heatindex_c: 29.3,
            heatindex_f: 84.7,
            dewpoint_c: 18,
            dewpoint_f: 64.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.1,
            uv: 1,
          },
          {
            time_epoch: 1695520800,
            time: "2023-09-23 22:00",
            temp_c: 27.7,
            temp_f: 81.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 63,
            wind_dir: "ENE",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 55,
            cloud: 44,
            feelslike_c: 28.8,
            feelslike_f: 83.8,
            windchill_c: 27.7,
            windchill_f: 81.8,
            heatindex_c: 28.8,
            heatindex_f: 83.8,
            dewpoint_c: 17.8,
            dewpoint_f: 64.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13,
            gust_kph: 20.9,
            uv: 1,
          },
          {
            time_epoch: 1695524400,
            time: "2023-09-23 23:00",
            temp_c: 26.8,
            temp_f: 80.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 90,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 59,
            cloud: 59,
            feelslike_c: 28,
            feelslike_f: 82.4,
            windchill_c: 26.8,
            windchill_f: 80.2,
            heatindex_c: 28,
            heatindex_f: 82.4,
            dewpoint_c: 18.1,
            dewpoint_f: 64.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.9,
            gust_kph: 28.7,
            uv: 1,
          },
        ],
      },
      {
        date: "2023-09-24",
        date_epoch: 1695513600,
        day: {
          maxtemp_c: 30.4,
          maxtemp_f: 86.8,
          mintemp_c: 23.7,
          mintemp_f: 74.7,
          avgtemp_c: 26.2,
          avgtemp_f: 79.2,
          maxwind_mph: 12.8,
          maxwind_kph: 20.5,
          totalprecip_mm: 3.99,
          totalprecip_in: 0.16,
          totalsnow_cm: 0,
          avgvis_km: 9.5,
          avgvis_miles: 5,
          avghumidity: 69,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 89,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 6,
        },
        astro: {
          sunrise: "07:20 AM",
          sunset: "07:25 PM",
          moonrise: "04:20 PM",
          moonset: "01:44 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: "63",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1695528000,
            time: "2023-09-24 00:00",
            temp_c: 25.6,
            temp_f: 78.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 95,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            humidity: 65,
            cloud: 42,
            feelslike_c: 27.1,
            feelslike_f: 80.7,
            windchill_c: 25.6,
            windchill_f: 78.1,
            heatindex_c: 27.1,
            heatindex_f: 80.7,
            dewpoint_c: 18.7,
            dewpoint_f: 65.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18,
            gust_kph: 28.9,
            uv: 1,
          },
          {
            time_epoch: 1695531600,
            time: "2023-09-24 01:00",
            temp_c: 24.9,
            temp_f: 76.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 93,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 68,
            cloud: 21,
            feelslike_c: 26.5,
            feelslike_f: 79.6,
            windchill_c: 24.9,
            windchill_f: 76.9,
            heatindex_c: 26.5,
            heatindex_f: 79.6,
            dewpoint_c: 18.7,
            dewpoint_f: 65.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18,
            gust_kph: 29,
            uv: 1,
          },
          {
            time_epoch: 1695535200,
            time: "2023-09-24 02:00",
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 11.2,
            wind_kph: 18,
            wind_degree: 92,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 66,
            cloud: 100,
            feelslike_c: 26.1,
            feelslike_f: 78.9,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 26.1,
            heatindex_f: 78.9,
            dewpoint_c: 17.9,
            dewpoint_f: 64.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.6,
            gust_kph: 26.7,
            uv: 1,
          },
          {
            time_epoch: 1695538800,
            time: "2023-09-24 03:00",
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 11,
            wind_kph: 17.6,
            wind_degree: 96,
            wind_dir: "E",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 13,
            feelslike_c: 26.2,
            feelslike_f: 79.1,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 26.2,
            heatindex_f: 79.1,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.3,
            gust_kph: 26.2,
            uv: 1,
          },
          {
            time_epoch: 1695542400,
            time: "2023-09-24 04:00",
            temp_c: 24.3,
            temp_f: 75.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 70,
            cloud: 12,
            feelslike_c: 25.9,
            feelslike_f: 78.7,
            windchill_c: 24.3,
            windchill_f: 75.7,
            heatindex_c: 25.9,
            heatindex_f: 78.7,
            dewpoint_c: 18.6,
            dewpoint_f: 65.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.6,
            gust_kph: 26.7,
            uv: 1,
          },
          {
            time_epoch: 1695546000,
            time: "2023-09-24 05:00",
            temp_c: 24.1,
            temp_f: 75.4,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 96,
            wind_dir: "E",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 98,
            feelslike_c: 26.3,
            feelslike_f: 79.4,
            windchill_c: 24.1,
            windchill_f: 75.4,
            heatindex_c: 26.3,
            heatindex_f: 79.4,
            dewpoint_c: 21.9,
            dewpoint_f: 71.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.8,
            gust_kph: 25.5,
            uv: 1,
          },
          {
            time_epoch: 1695549600,
            time: "2023-09-24 06:00",
            temp_c: 23.8,
            temp_f: 74.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 102,
            wind_dir: "ESE",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            humidity: 73,
            cloud: 14,
            feelslike_c: 25.6,
            feelslike_f: 78.1,
            windchill_c: 23.9,
            windchill_f: 74.9,
            heatindex_c: 25.6,
            heatindex_f: 78.1,
            dewpoint_c: 18.7,
            dewpoint_f: 65.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.6,
            gust_kph: 25.1,
            uv: 1,
          },
          {
            time_epoch: 1695553200,
            time: "2023-09-24 07:00",
            temp_c: 23.7,
            temp_f: 74.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 106,
            wind_dir: "ESE",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            humidity: 74,
            cloud: 16,
            feelslike_c: 25.5,
            feelslike_f: 77.9,
            windchill_c: 23.7,
            windchill_f: 74.7,
            heatindex_c: 25.5,
            heatindex_f: 77.9,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.6,
            gust_kph: 23.4,
            uv: 1,
          },
          {
            time_epoch: 1695556800,
            time: "2023-09-24 08:00",
            temp_c: 24.1,
            temp_f: 75.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 105,
            wind_dir: "ESE",
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 91,
            cloud: 34,
            feelslike_c: 26.5,
            feelslike_f: 79.7,
            windchill_c: 24.1,
            windchill_f: 75.4,
            heatindex_c: 26.5,
            heatindex_f: 79.7,
            dewpoint_c: 22.5,
            dewpoint_f: 72.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13,
            gust_kph: 20.8,
            uv: 6,
          },
          {
            time_epoch: 1695560400,
            time: "2023-09-24 09:00",
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 104,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 72,
            cloud: 14,
            feelslike_c: 26.3,
            feelslike_f: 79.3,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 26.3,
            heatindex_f: 79.3,
            dewpoint_c: 19.3,
            dewpoint_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13,
            gust_kph: 20.9,
            uv: 6,
          },
          {
            time_epoch: 1695564000,
            time: "2023-09-24 10:00",
            temp_c: 26.2,
            temp_f: 79.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 106,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 67,
            cloud: 13,
            feelslike_c: 27.8,
            feelslike_f: 82,
            windchill_c: 26.2,
            windchill_f: 79.1,
            heatindex_c: 27.8,
            heatindex_f: 82,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.8,
            gust_kph: 20.6,
            uv: 7,
          },
          {
            time_epoch: 1695567600,
            time: "2023-09-24 11:00",
            temp_c: 27.4,
            temp_f: 81.3,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 109,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 74,
            cloud: 100,
            feelslike_c: 30.3,
            feelslike_f: 86.6,
            windchill_c: 27.4,
            windchill_f: 81.3,
            heatindex_c: 30.3,
            heatindex_f: 86.6,
            dewpoint_c: 22.4,
            dewpoint_f: 72.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.4,
            gust_kph: 20,
            uv: 6,
          },
          {
            time_epoch: 1695571200,
            time: "2023-09-24 12:00",
            temp_c: 28.9,
            temp_f: 84,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 100,
            wind_dir: "E",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 55,
            cloud: 11,
            feelslike_c: 30.5,
            feelslike_f: 86.8,
            windchill_c: 28.9,
            windchill_f: 84,
            heatindex_c: 30.5,
            heatindex_f: 86.8,
            dewpoint_c: 19,
            dewpoint_f: 66.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.1,
            gust_kph: 19.5,
            uv: 7,
          },
          {
            time_epoch: 1695574800,
            time: "2023-09-24 13:00",
            temp_c: 29.8,
            temp_f: 85.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 87,
            wind_dir: "E",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 51,
            cloud: 12,
            feelslike_c: 31.3,
            feelslike_f: 88.4,
            windchill_c: 29.8,
            windchill_f: 85.7,
            heatindex_c: 31.3,
            heatindex_f: 88.4,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.1,
            gust_kph: 17.8,
            uv: 7,
          },
          {
            time_epoch: 1695578400,
            time: "2023-09-24 14:00",
            temp_c: 28.6,
            temp_f: 83.5,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 94,
            wind_dir: "E",
            pressure_mb: 1014,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 65,
            cloud: 100,
            feelslike_c: 31.3,
            feelslike_f: 88.3,
            windchill_c: 28.6,
            windchill_f: 83.5,
            heatindex_c: 31.3,
            heatindex_f: 88.3,
            dewpoint_c: 21.4,
            dewpoint_f: 70.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 6,
          },
          {
            time_epoch: 1695582000,
            time: "2023-09-24 15:00",
            temp_c: 30.4,
            temp_f: 86.8,
            is_day: 1,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
              code: 1153,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 103,
            wind_dir: "ESE",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.61,
            precip_in: 0.02,
            humidity: 50,
            cloud: 76,
            feelslike_c: 32.1,
            feelslike_f: 89.8,
            windchill_c: 30.4,
            windchill_f: 86.8,
            heatindex_c: 32.1,
            heatindex_f: 89.8,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 0,
            chance_of_rain: 62,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 7,
          },
          {
            time_epoch: 1695585600,
            time: "2023-09-24 16:00",
            temp_c: 28.4,
            temp_f: 83.1,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 136,
            wind_dir: "SE",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 1.54,
            precip_in: 0.06,
            humidity: 61,
            cloud: 82,
            feelslike_c: 30.4,
            feelslike_f: 86.7,
            windchill_c: 28.4,
            windchill_f: 83.1,
            heatindex_c: 30.4,
            heatindex_f: 86.7,
            dewpoint_c: 20,
            dewpoint_f: 68,
            will_it_rain: 0,
            chance_of_rain: 62,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 12.8,
            gust_kph: 20.6,
            uv: 6,
          },
          {
            time_epoch: 1695589200,
            time: "2023-09-24 17:00",
            temp_c: 28.2,
            temp_f: 82.8,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 165,
            wind_dir: "SSE",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 65,
            cloud: 98,
            feelslike_c: 30.6,
            feelslike_f: 87.2,
            windchill_c: 28.2,
            windchill_f: 82.8,
            heatindex_c: 30.6,
            heatindex_f: 87.2,
            dewpoint_c: 21.1,
            dewpoint_f: 69.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.3,
            gust_kph: 11.8,
            uv: 6,
          },
          {
            time_epoch: 1695592800,
            time: "2023-09-24 18:00",
            temp_c: 27,
            temp_f: 80.6,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 139,
            wind_dir: "SE",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 1.24,
            precip_in: 0.05,
            humidity: 68,
            cloud: 50,
            feelslike_c: 29,
            feelslike_f: 84.2,
            windchill_c: 27,
            windchill_f: 80.6,
            heatindex_c: 29,
            heatindex_f: 84.2,
            dewpoint_c: 20.6,
            dewpoint_f: 69,
            will_it_rain: 1,
            chance_of_rain: 71,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3,
            gust_kph: 4.9,
            uv: 6,
          },
          {
            time_epoch: 1695596400,
            time: "2023-09-24 19:00",
            temp_c: 27,
            temp_f: 80.6,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 102,
            wind_dir: "ESE",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0.06,
            precip_in: 0,
            humidity: 68,
            cloud: 71,
            feelslike_c: 29.1,
            feelslike_f: 84.3,
            windchill_c: 27,
            windchill_f: 80.6,
            heatindex_c: 29.1,
            heatindex_f: 84.3,
            dewpoint_c: 20.7,
            dewpoint_f: 69.3,
            will_it_rain: 1,
            chance_of_rain: 89,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.4,
            gust_kph: 10.2,
            uv: 6,
          },
          {
            time_epoch: 1695600000,
            time: "2023-09-24 20:00",
            temp_c: 26.5,
            temp_f: 79.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 95,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 72,
            cloud: 45,
            feelslike_c: 28.6,
            feelslike_f: 83.5,
            windchill_c: 26.5,
            windchill_f: 79.7,
            heatindex_c: 28.6,
            heatindex_f: 83.5,
            dewpoint_c: 21,
            dewpoint_f: 69.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 9.6,
            gust_kph: 15.4,
            uv: 1,
          },
          {
            time_epoch: 1695603600,
            time: "2023-09-24 21:00",
            temp_c: 26.1,
            temp_f: 79,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 103,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0.54,
            precip_in: 0.02,
            humidity: 74,
            cloud: 86,
            feelslike_c: 28.3,
            feelslike_f: 82.9,
            windchill_c: 26.1,
            windchill_f: 79,
            heatindex_c: 28.3,
            heatindex_f: 82.9,
            dewpoint_c: 21.2,
            dewpoint_f: 70.1,
            will_it_rain: 1,
            chance_of_rain: 75,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 11.9,
            gust_kph: 19.2,
            uv: 1,
          },
          {
            time_epoch: 1695607200,
            time: "2023-09-24 22:00",
            temp_c: 25.6,
            temp_f: 78.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 110,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 77,
            cloud: 28,
            feelslike_c: 27.8,
            feelslike_f: 82,
            windchill_c: 25.7,
            windchill_f: 78.2,
            heatindex_c: 27.8,
            heatindex_f: 82,
            dewpoint_c: 21.2,
            dewpoint_f: 70.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.5,
            gust_kph: 21.8,
            uv: 1,
          },
          {
            time_epoch: 1695610800,
            time: "2023-09-24 23:00",
            temp_c: 25,
            temp_f: 77,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 115,
            wind_dir: "ESE",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 14,
            feelslike_c: 27.1,
            feelslike_f: 80.9,
            windchill_c: 25,
            windchill_f: 77,
            heatindex_c: 27.1,
            heatindex_f: 80.9,
            dewpoint_c: 21.5,
            dewpoint_f: 70.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.4,
            gust_kph: 23.2,
            uv: 1,
          },
        ],
      },
    ],
  },
};
export default example;
